from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from pydantic import BaseModel, Field

from ..contracts import (
    DSLOperationName,
    InvestigationDecision,
    InvestigationHypothesis,
    StopReason,
)


class InvestigationProposal(BaseModel):
    """Structured proposal generated by Google Gemini / ADK Planner."""
    goal: str = Field(description="High-level diagnostic goal of the proposed experiment.")
    proposed_operation: DSLOperationName = Field(description="Restricted DSL operation proposed from catalog.")
    args: dict[str, Any] = Field(default_factory=dict, description="Validated parameter arguments for the operation.")
    target_hypotheses: list[str] = Field(default_factory=list, description="Hypotheses intended to discriminate or challenge.")
    rationale: str = Field(default="", description="Detailed scientific justification for selecting this test.")
    expected_discrimination: str = Field(default="", description="Expected outcome distinction between candidate hypotheses.")


class AgentExecutionProvenance(BaseModel):
    """Cryptographic audit record of Google ADK / Gemini proposal and ASTRA execution."""
    turn: int = Field(default=1, description="Investigation turn index.")
    agent_framework: str = Field(default="Google ADK", description="Google Agent Framework used.")
    model_provider: str = Field(default="Google", description="Underlying Foundation Model Provider.")
    model: str = Field(description="Exact Gemini model identifier used.")
    proposal: InvestigationProposal = Field(description="Structured proposal emitted by agent.")
    astra_validation_passed: bool = Field(description="Whether ASTRA DSL validator approved the proposal.")
    validation_error: str | None = Field(default=None, description="Rejection reason if validation failed.")
    executed_operation: str | None = Field(default=None, description="Actual operation executed in deterministic sandbox.")
    evidence_generated: list[dict[str, Any]] = Field(default_factory=list, description="Evidence items produced by execution.")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    trace_id: str = Field(description="Unique distributed trace identifier.")


class GoogleAgentReport(BaseModel):
    """End-to-end investigation result package generated with Google ADK / Gemini."""
    case_id: str
    trace_id: str
    scenario_name: str = "hero"
    runtime: str = Field(description="Execution runtime environment ('Google Cloud Run' or 'local').")
    agent_framework: str = "Google ADK"
    agent_name: str = "astra_investigation_planner"
    model_provider: str = "Google"
    model: str
    execution_boundary: str = "ASTRA Restricted DSL"
    initial_anomaly_idx: int
    proposals_count: int = 0
    proposals_accepted: int = 0
    proposals_rejected: int = 0
    executed_operations: list[str] = Field(default_factory=list)
    competing_hypotheses: list[dict[str, Any]] = Field(default_factory=list)
    stop_reason: StopReason
    decision: InvestigationDecision
    decision_reliability_score: float
    primary_reason: str
    counterfactuals: list[dict[str, Any]] = Field(default_factory=list)
    provenance_records: list[AgentExecutionProvenance] = Field(default_factory=list)
    series_preview: list[float] = Field(default_factory=list)
    duration_ms: float = 0.0
